execfile('co_intmaps.py')
execfile('continuum_figures.py')
execfile('dendrogram_bgps.py')
execfile('dens_histogram.py')
execfile('dens_histograms_compare.py')
execfile('density_fit_contour_example.py')
execfile('h2co_velo_images.py')
execfile('largescale_aplpy.py')
execfile('lineplots.py')
execfile('mpld3plot.py')
execfile('offspectra_plots.py')
execfile('parplots.py')
execfile('parplots_chi2gridfit.py')
execfile('paths.py')
execfile('projection_figures.py')
execfile('rrl_images.py')
execfile('specgrid.py')
execfile('tau_histograms.py')

#execfile('co_vs_h2co.py')
#execfile('opticaldepth_plots.py')

#execfile('aplpy_figure_maker.py')
#execfile('common_constants.py')
#execfile('velo_cmap.py')
#execfile('load_pyspeckit_cubes.py')
