# Simple script to run all analysis commands sequentially
# (should take quite a while)

execfile('make_taucubes.py')
execfile('contcompare_dc_2cm.py')
execfile('contcompare_dc_6cm.py')
execfile('digging_in_to_G49.27-0.34.py')
execfile('get_simbad_regions.py')
execfile('integrated_h2co_properties.py')
execfile('merge_apertures.py')
execfile('pyspeckit_cube_fit_justlineprops.py')
execfile('pyspeckit_cube_fit_textau.py')
execfile('pyspeckit_individual_spectra.py')
execfile('examine_one_spectrum.py')
execfile('density_fit.py')
execfile('radial_profiles.py')
execfile('radial_velocity_dispersion.py')
execfile('co_intmaps.py')
execfile('rrl_average.py')
execfile('pyspeckit_RRL_cube_fit.py')
execfile('rrl_analysis.py')
